/**
 * Interface for summary data
 */

export type SummaryData =
    | 'acetonePpm'
    | 'weight'
    | 'bmi'
    | 'fatFreeMass'
    | 'bodyFat'
    | 'fatMassWeight'
    | 'bloodPressureDiastolic'
    | 'bloodPressureSystolic'
    | 'heartRate'
    | 'bloodOxygenLevel'
    | 'boneWeight'
    | 'basalMetabolicRate'
    | 'musclePercentage'
    | 'visceralFatPercentage'
    | 'waterPercentage'
    | 'waist'
    | 'arm'
    | 'hip'
    | 'chest'
    | 'thigh'
    | 'neck'
    | 'thorax'
    | 'totalCholesterol'
    | 'ldl'
    | 'hdl'
    | 'vldl'
    | 'triglycerides'
    | 'fastingGlucose'
    | 'hba1c'
    | 'insulin'
    | 'hsCrp'
    | 'temperature'
    | 'respirationRate'
    | 'visceralFatTanita';
