version: 2.1

orbs:
  aws-code-deploy: circleci/aws-code-deploy@0.0.9
  aws-cli: circleci/aws-cli@0.1.16

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.16.3

yarn_auth: &yarn_auth
  name: Set up .npmrc (auth)
  command: |
    sudo echo "registry=https://$NPM_REGISTRY" > ~/.npmrc
    sudo echo "//$NPM_REGISTRY:_authToken=\"$NPM_AUTH_TOKEN\"" >> ~/.npmrc
    sudo echo "//$NPM_REGISTRY:always-auth=true" >> ~/.npmrc
    sudo echo "//npm.pkg.github.com/:_authToken=\"$COACHCARE_AUTH_TOKEN\"" >> ~/.npmrc
    sudo echo "@coachcare:registry=https://npm.pkg.github.com/" >> ~/.npmrc
npm_dependency_installation: &npm_dependency_installation
  name: Installing NPM dependencies
  command: |
    attempts=0
    until [ $attempts -ge 5 ]
    do
        yarn install --frozen-lockfile && break
        attempts=$[$attempts+1]
        echo "yarn install attempt $attempts failed, retrying"
    done
    if [ $attempts -ge 5 ]; then
        exit 5
    fi
dependency_cache_key: &dependency_cache_key dependency-cache-{{ checksum "yarn.lock" }}

jobs:
  setup:
    <<: *defaults
    steps:
      - run:
          name: Echo
          command: echo "Hello"

  affected_lint:
    <<: *defaults
    steps:
      - run:
          name: Echo
          command: echo "Hello"

  affected_build:
    <<: *defaults
    steps:
      - run:
          name: Echo
          command: echo "Hello"

  affected_test:
    <<: *defaults
    steps:
      - run:
          name: Echo
          command: echo "Hello"

  affected_e2e:
    <<: *defaults
    steps:
      - run:
          name: Echo
          command: echo "Hello"
  full_test_build:
    <<: *defaults
    steps:
      - run:
          name: Echo
          command: echo "Hello"
  full_production_build:
    <<: *defaults
    steps:
      - run:
          name: Echo
          command: echo "Hello"
  deploy_to_test:
    <<: *defaults
    steps:
      - run:
          name: Echo
          command: echo "Hello"

  deploy_to_production:
    <<: *defaults
    steps:
      - run:
          name: Echo
          command: echo "Hello"

  format_check:
    <<: *defaults
    steps:
      - run:
          name: Echo
          command: echo "Hello"

workflows:
  setup_build_deploy:
    jobs:
      - setup
      - affected_lint
      #    requires:
      #      - setup
      - affected_build
      #     requires:
      #       - setup
      - affected_test
      #     requires:
      #       - affected_build
      # - affected_e2e:
      # requires:
      # - affected_build
      - affected_test
      - format_check
      - full_test_build
      #     requires:
      # - setup
      # - affected_lint
      # - affected_test
      # - affected_e2e
      # - approve_test_deployment:
      #     type: approval
      #     filters:
      #       branches:
      #         ignore:
      #           - master
      #     requires:
      #       - full_test_build
      # - deploy_to_test:
      #     requires:
      #       - approve_test_deployment
      #       - full_test_build
      #     context: site-deployment-test
      # - full_production_build:
      #     filters:
      #       branches:
      #         only:
      #           - master
      #     requires:
      #       - deploy_to_test
      # - approve_production_deployment:
      #     filters:
      #       branches:
      #         only:
      #           - master
      #     type: approval
      #     requires:
      #       - full_production_build
      # - deploy_to_production:
      #     filters:
      #       branches:
      #         only:
      #           - master
      #     requires:
      #       - approve_production_deployment
      # context: site-deployment-prod
