import {
  ActiveCampaign,
  ApiService,
  ContentPreference,
  MFA,
  Organization as SelveraOrganizationService,
  RPM,
  Sequence
} from 'selvera-api';
import {
  Account,
  AccountAvatar,
  AccountPassword,
  AccountPreference,
  Alerts,
  AlertsPreference,
  AlertsPreferenceAccount,
  Blacklist,
  CommunicationPreference,
  ConferenceBilling,
  ConferenceCall,
  ConferenceSubaccount,
  Consent,
  ConsentTos,
  Content,
  ContentPackage,
  Countries,
  Exercise,
  ExerciseAssociation,
  ExerciseType,
  ExternalAuth,
  ExternalDevice,
  ExternalGoogleAuth,
  Feedback,
  Food,
  FoodConsumed,
  FoodFavorite,
  FoodIngredient,
  FoodIngredientLocale,
  FoodKeyLocale,
  FoodMeal,
  FoodMealLocale,
  FoodMealOrganization,
  FoodMealPlanLocale,
  FoodMealPlanTypeLocale,
  FoodMealServing,
  FoodPreference,
  FoodServing,
  FoodServingLocale,
  Form,
  FormAddendum,
  FormQuestion,
  FormQuestionType,
  FormSection,
  FormSubmission,
  Goal,
  Hydration,
  Idealshape,
  Key,
  KeyAccount,
  KeyConsumed,
  KeyOrganization,
  LocalePackage,
  LocaleSupplement,
  Logging,
  MeasurementActivity,
  MeasurementBody,
  MeasurementSleep,
  Meeting,
  MeetingAttendee,
  MeetingType,
  MeetingTypeOrganization,
  Messaging,
  MessagingPermission,
  MessagingPreference,
  MobileApp,
  MobilePushClient,
  NoteConsultation,
  NoteGeneral,
  Nutrition,
  Organization,
  OrganizationAssignment,
  OrganizationAssociation,
  OrganizationPreference,
  Package,
  PackageEnrollment,
  PackageOrganization,
  PainTracking,
  Register,
  Reports,
  ScheduleAvailable,
  SchedulePreferences,
  Scheduler,
  ScheduleReports,
  Session,
  Stripe,
  Supplement,
  SupplementAccountOrganization,
  SupplementConsumption,
  SupplementOrganization,
  System
} from './index';

export const GatewayProviders = [
  Account,
  AccountAvatar,
  AccountPassword,
  AccountPreference,
  Alerts,
  AlertsPreference,
  AlertsPreferenceAccount,
  Blacklist,
  CommunicationPreference,
  ConferenceBilling,
  ConferenceCall,
  ConferenceSubaccount,
  Consent,
  ConsentTos,
  Content,
  ContentPackage,
  Countries,
  Exercise,
  ExerciseAssociation,
  ExerciseType,
  ExternalAuth,
  ExternalDevice,
  ExternalGoogleAuth,
  Feedback,
  Food,
  FoodConsumed,
  FoodFavorite,
  FoodIngredient,
  FoodIngredientLocale,
  FoodKeyLocale,
  FoodMeal,
  FoodMealLocale,
  FoodMealOrganization,
  FoodMealPlanLocale,
  FoodMealPlanTypeLocale,
  FoodMealServing,
  FoodPreference,
  FoodServing,
  FoodServingLocale,
  Form,
  FormAddendum,
  FormQuestion,
  FormQuestionType,
  FormSection,
  FormSubmission,
  Goal,
  Hydration,
  Idealshape,
  Key,
  KeyAccount,
  KeyConsumed,
  KeyOrganization,
  LocalePackage,
  LocaleSupplement,
  Logging,
  MeasurementActivity,
  MeasurementBody,
  MeasurementSleep,
  Meeting,
  MeetingAttendee,
  MeetingType,
  MeetingTypeOrganization,
  Messaging,
  MessagingPermission,
  MessagingPreference,
  MobileApp,
  MobilePushClient,
  NoteConsultation,
  NoteGeneral,
  Nutrition,
  Organization,
  OrganizationAssignment,
  OrganizationAssociation,
  OrganizationPreference,
  PackageEnrollment,
  PainTracking,
  Register,
  Reports,
  ScheduleAvailable,
  SchedulePreferences,
  Scheduler,
  ScheduleReports,
  Session,
  Stripe,
  Supplement,
  SupplementAccountOrganization,
  SupplementConsumption,
  SupplementOrganization,
  System
];

export const SelveraProviders = [
  {
    provide: ActiveCampaign,
    useClass: ActiveCampaign,
    deps: [ApiService]
  },
  {
    provide: Sequence,
    useClass: Sequence,
    deps: [ApiService]
  },
  {
    provide: MFA,
    useClass: MFA,
    deps: [ApiService]
  },
  {
    provide: Package,
    useClass: Package,
    deps: [ApiService]
  },
  {
    provide: PackageOrganization,
    useClass: PackageOrganization,
    deps: [ApiService]
  },
  {
    provide: RPM,
    useClass: RPM,
    deps: [ApiService]
  },
  {
    provide: SelveraOrganizationService,
    useClass: SelveraOrganizationService,
    deps: [ApiService]
  },
  {
    provide: ContentPreference,
    useClass: ContentPreference,
    deps: [ApiService]
  }
];
