export * from './clinic-listing.details'
export * from './journal.details'
export * from './patient-form.details'
export * from './patient-listing.details'
export * from './right-panel.details'
export * from './rpm.details'
export * from './sidenav.details'
export * from './cohort-reports.details'
