export const rpmData = [
  {
    ID: '6154',
    'First Name': 'Lascario',
    'Last Name': 'Pacheco',
    'Date of Birth': '06/10/1994',
    'Device Type': 'BALANCE Smart Scale',
    'Primary Diagnosis': 'Primary Diagnosis 123',
    'Secondary Diagnosis': 'Secondary Diagnosis 123',
    'Supervising Provider': 'Lascario Pacheco Arrieta',
    'Organization ID': '7556',
    'Organization Name': 'Alaska Premier Health - Parent Org',
    Status: 'Active',
    'Activation Date': '05/01/2023',
    'Billing Type': '',
    'Monitoring Type': '',
    'Latest Claim Date 99453': 'N/A',
    'Next Claim Requirements 99453': '30 more calendar days; ',
    'Latest Claim Date 99454': 'N/A',
    'Next Claim Requirements 99454':
      '30 more calendar days; 15 more device transmissions needed',
    'Latest Claim Date 99457': 'N/A',
    'Next Claim Requirements 99457':
      '30 more calendar days; 20 minutes more of monitoring needed; 1 more live interactions (call/visit) needed',
    'Latest Claim Date 99458 (1)': 'N/A',
    'Next Claim Requirements 99458 (1)':
      '99457 requirements not satisfied; 30 more calendar days; 20 minutes more of monitoring needed',
    'Latest Claim Date 99458 (2)': 'N/A',
    'Next Claim Requirements 99458 (2)':
      '99458 requirements not satisfied; 30 more calendar days; 20 minutes more of monitoring needed'
  },
  {
    ID: '6737',
    'First Name': 'A',
    'Last Name': 'A',
    'Date of Birth': '04/26/1993',
    'Device Type': 'Pulse Oximeter',
    'Primary Diagnosis': 'see',
    'Secondary Diagnosis': 'wee',
    'Supervising Provider': 'Eric Di Bari',
    'Organization ID': '7047',
    'Organization Name': 'CoachCare Clinic Test',
    Status: 'Active',
    'Activation Date': '04/06/2023',
    'Billing Type': '',
    'Monitoring Type': '',
    'Latest Claim Date 99453': '01/31/2020',
    'Next Claim Requirements 99453': 'N/A',
    'Latest Claim Date 99454': '01/31/2020',
    'Next Claim Requirements 99454': 'N/A',
    'Latest Claim Date 99457': '01/31/2020',
    'Next Claim Requirements 99457': 'N/A',
    'Latest Claim Date 99458 (1)': '01/31/2020',
    'Next Claim Requirements 99458 (1)': 'N/A',
    'Latest Claim Date 99458 (2)': 'N/A',
    'Next Claim Requirements 99458 (2)': ''
  },
  {
    ID: '7226',
    'First Name': '0000 0000 - Eric Clinic',
    'Last Name': 'Patient',
    'Date of Birth': '02/19/2004',
    'Device Type': 'Pulse Oximeter',
    'Primary Diagnosis': 'test',
    'Secondary Diagnosis': 'test 2',
    'Supervising Provider': 'Jeffrey Drakos',
    'Organization ID': '30',
    'Organization Name': 'CoachCare',
    Status: 'Active',
    'Activation Date': '04/15/2023',
    'Billing Type': '',
    'Monitoring Type': '',
    'Latest Claim Date 99453': '01/31/2020',
    'Next Claim Requirements 99453': 'N/A',
    'Latest Claim Date 99454': '01/31/2020',
    'Next Claim Requirements 99454': 'N/A',
    'Latest Claim Date 99457': '01/31/2020',
    'Next Claim Requirements 99457': 'N/A',
    'Latest Claim Date 99458 (1)': '01/31/2020',
    'Next Claim Requirements 99458 (1)': 'N/A',
    'Latest Claim Date 99458 (2)': 'N/A',
    'Next Claim Requirements 99458 (2)': '20 minutes more of monitoring needed'
  },
  {
    ID: '7474',
    'First Name': 'Zhang',
    'Last Name': '123',
    'Date of Birth': '11/22/1984',
    'Device Type': 'BEAT Blood Pressure Cuff',
    'Primary Diagnosis': 'Test',
    'Secondary Diagnosis': '',
    'Supervising Provider': 'Jeffrey Drakos',
    'Organization ID': '30',
    'Organization Name': 'CoachCare',
    Status: 'Active',
    'Activation Date': '04/28/2023',
    'Billing Type': '',
    'Monitoring Type': '',
    'Latest Claim Date 99453': '01/31/2020',
    'Next Claim Requirements 99453': 'N/A',
    'Latest Claim Date 99454': 'N/A',
    'Next Claim Requirements 99454':
      '20 more calendar days; 15 more device transmissions needed',
    'Latest Claim Date 99457': 'N/A',
    'Next Claim Requirements 99457':
      '30 more calendar days; 20 minutes more of monitoring needed; 1 more live interactions (call/visit) needed',
    'Latest Claim Date 99458 (1)': 'N/A',
    'Next Claim Requirements 99458 (1)':
      '99457 requirements not satisfied; 30 more calendar days; 20 minutes more of monitoring needed',
    'Latest Claim Date 99458 (2)': 'N/A',
    'Next Claim Requirements 99458 (2)':
      '99458 requirements not satisfied; 30 more calendar days; 20 minutes more of monitoring needed'
  },
  {
    ID: '9333',
    'First Name': 'Eric',
    'Last Name': 'Di Bari',
    'Date of Birth': '01/01/2000',
    'Device Type': 'BEAT Blood Pressure Cuff',
    'Primary Diagnosis': 'test',
    'Secondary Diagnosis': 'test',
    'Supervising Provider': 'Eric Di Bari',
    'Organization ID': '31',
    'Organization Name': 'CoachCare Clinic Test NY',
    Status: 'Active',
    'Activation Date': '04/27/2023',
    'Billing Type': '',
    'Monitoring Type': '',
    'Latest Claim Date 99453': '01/31/2020',
    'Next Claim Requirements 99453': 'N/A',
    'Latest Claim Date 99454': '01/31/2020',
    'Next Claim Requirements 99454': 'N/A',
    'Latest Claim Date 99457': 'N/A',
    'Next Claim Requirements 99457':
      '20 more calendar days; 10 minutes more of monitoring needed; 1 more live interactions (call/visit) needed',
    'Latest Claim Date 99458 (1)': 'N/A',
    'Next Claim Requirements 99458 (1)':
      '99457 requirements not satisfied; 30 more calendar days; 20 minutes more of monitoring needed',
    'Latest Claim Date 99458 (2)': 'N/A',
    'Next Claim Requirements 99458 (2)':
      '99458 requirements not satisfied; 30 more calendar days; 20 minutes more of monitoring needed'
  }
]

export const ccmData = [
  {
    ID: '6708',
    'First Name': 'A',
    'Last Name': 'A',
    'Date of Birth': '04/25/1993',
    'Primary Diagnosis': 'test',
    'Secondary Diagnosis': 'testasdsd',
    'Supervising Provider': 'Eric Di Bari',
    'Organization ID': '7048',
    'Organization Name': 'CoachCare Clinic Test',
    Status: 'Active',
    'Activation Date': '01/31/2020',
    'Billing Type': '',
    'Monitoring Type': '',
    'Latest Claim Date 99490': 'N/A',
    'Next Claim Requirements 99490':
      '30 more calendar days; 20 minutes more of monitoring needed',
    'Latest Claim Date 99439 (1)': 'N/A',
    'Next Claim Requirements 99439 (1)':
      '99490 requirements not satisfied; 30 more calendar days; 20 minutes more of monitoring needed',
    'Latest Claim Date 99439 (2)': 'N/A',
    'Next Claim Requirements 99439 (2)':
      '99439 requirements not satisfied; 30 more calendar days; 20 minutes more of monitoring needed'
  },
  {
    ID: '6738',
    'First Name': 'A',
    'Last Name': 'A',
    'Date of Birth': '03/26/1971',
    'Primary Diagnosis': 'test',
    'Secondary Diagnosis': 'test2 qwqwqwqwwq',
    'Supervising Provider': 'Eric Di Bari',
    'Organization ID': '6997',
    'Organization Name': 'Coachcare FRON-740',
    Status: 'Active',
    'Activation Date': '01/31/2020',
    'Billing Type': '',
    'Monitoring Type': '',
    'Latest Claim Date 99490': '01/31/2020',
    'Next Claim Requirements 99490': 'N/A',
    'Latest Claim Date 99439 (1)': 'N/A',
    'Next Claim Requirements 99439 (1)':
      '30 more calendar days; 15 minutes more of monitoring needed',
    'Latest Claim Date 99439 (2)': 'N/A',
    'Next Claim Requirements 99439 (2)':
      '99439 requirements not satisfied; 30 more calendar days; 20 minutes more of monitoring needed'
  },
  {
    ID: '7255',
    'First Name': 'An underage patient',
    'Last Name': 'An underage patient',
    'Date of Birth': '03/12/2001',
    'Primary Diagnosis': 'test',
    'Secondary Diagnosis': 'test',
    'Supervising Provider': 'Jeffrey Drakos',
    'Organization ID': '30',
    'Organization Name': 'CoachCare',
    Status: 'Active',
    'Activation Date': '02/01/2020',
    'Billing Type': '',
    'Monitoring Type': '',
    'Latest Claim Date 99490': '01/31/2020',
    'Next Claim Requirements 99490': 'N/A',
    'Latest Claim Date 99439 (1)': '01/31/2020',
    'Next Claim Requirements 99439 (1)': 'N/A',
    'Latest Claim Date 99439 (2)': 'N/A',
    'Next Claim Requirements 99439 (2)': '10 minutes more of monitoring needed'
  },
  {
    ID: '7470',
    'First Name': 'Zhang',
    'Last Name': 'Xin',
    'Date of Birth': '07/22/1994',
    'Primary Diagnosis': 'sdd',
    'Secondary Diagnosis': 'sdd',
    'Supervising Provider': 'Jeffrey Drakos',
    'Organization ID': '30',
    'Organization Name': 'CoachCare',
    Status: 'Active',
    'Activation Date': '02/01/2020',
    'Billing Type': '',
    'Monitoring Type': '',
    'Latest Claim Date 99490': '01/31/2020',
    'Next Claim Requirements 99490': 'N/A',
    'Latest Claim Date 99439 (1)': '01/31/2020',
    'Next Claim Requirements 99439 (1)': 'N/A',
    'Latest Claim Date 99439 (2)': '01/31/2020',
    'Next Claim Requirements 99439 (2)': 'N/A'
  }
]

export const rtmData = [
  {
    ID: '6154',
    'First Name': 'Lascario',
    'Last Name': 'Pacheco',
    'Date of Birth': '06/10/1994',
    'Device Type': 'SCAN Smart Glucometer',
    'Primary Diagnosis': 'Primary Diagnosis 123',
    'Secondary Diagnosis': 'Secondary Diagnosis 123',
    'Supervising Provider': 'Lascario Pacheco Arrieta',
    'Organization ID': '7556',
    'Organization Name': 'Alaska Premier Health - Parent Org',
    Status: 'Active',
    'Activation Date': '05/01/2023',
    'Billing Type': '',
    'Monitoring Type': '',
    'Latest Claim Date 98975': 'N/A',
    'Next Claim Requirements 98975': '30 more calendar days; ',
    'Latest Claim Date 98977': 'N/A',
    'Next Claim Requirements 98977':
      '30 more calendar days; 15 more device transmissions needed',
    'Latest Claim Date 98980': 'N/A',
    'Next Claim Requirements 98980':
      '30 more calendar days; 20 minutes more of monitoring needed; 1 more live interactions (call/visit) needed',
    'Latest Claim Date 98981 (1)': 'N/A',
    'Next Claim Requirements 98981 (1)':
      '98980 requirements not satisfied; 30 more calendar days; 20 minutes more of monitoring needed',
    'Latest Claim Date 98981 (2)': 'N/A',
    'Next Claim Requirements 98981 (2)':
      '98981 requirements not satisfied; 30 more calendar days; 20 minutes more of monitoring needed'
  },
  {
    ID: '6737',
    'First Name': 'A',
    'Last Name': 'A',
    'Date of Birth': '04/26/1993',
    'Device Type': 'Pulse Oximeter',
    'Primary Diagnosis': 'see',
    'Secondary Diagnosis': 'wee',
    'Supervising Provider': 'Eric Di Bari',
    'Organization ID': '7047',
    'Organization Name': 'CoachCare Clinic Test',
    Status: 'Active',
    'Activation Date': '04/06/2023',
    'Billing Type': '',
    'Monitoring Type': '',
    'Latest Claim Date 98975': '01/31/2020',
    'Next Claim Requirements 98975': 'N/A',
    'Latest Claim Date 98977': '01/31/2020',
    'Next Claim Requirements 98977': 'N/A',
    'Latest Claim Date 98980': '01/31/2020',
    'Next Claim Requirements 98980': 'N/A',
    'Latest Claim Date 98981 (1)': '01/31/2020',
    'Next Claim Requirements 98981 (1)': 'N/A',
    'Latest Claim Date 98981 (2)': 'N/A',
    'Next Claim Requirements 98981 (2)': ''
  },
  {
    ID: '7226',
    'First Name': '0000 0000 - Eric Clinic',
    'Last Name': 'Patient',
    'Date of Birth': '02/19/2004',
    'Device Type': 'Pulse Oximeter',
    'Primary Diagnosis': 'test',
    'Secondary Diagnosis': 'test 2',
    'Supervising Provider': 'Jeffrey Drakos',
    'Organization ID': '30',
    'Organization Name': 'CoachCare',
    Status: 'Active',
    'Activation Date': '04/15/2023',
    'Billing Type': '',
    'Monitoring Type': '',
    'Latest Claim Date 98975': '01/31/2020',
    'Next Claim Requirements 98975': 'N/A',
    'Latest Claim Date 98977': '01/31/2020',
    'Next Claim Requirements 98977': 'N/A',
    'Latest Claim Date 98980': '01/31/2020',
    'Next Claim Requirements 98980': 'N/A',
    'Latest Claim Date 98981 (1)': '01/31/2020',
    'Next Claim Requirements 98981 (1)': 'N/A',
    'Latest Claim Date 98981 (2)': 'N/A',
    'Next Claim Requirements 98981 (2)': '20 minutes more of monitoring needed'
  },
  {
    ID: '7474',
    'First Name': 'Zhang',
    'Last Name': '123',
    'Date of Birth': '11/22/1984',
    'Device Type': 'BEAT Blood Pressure Cuff',
    'Primary Diagnosis': 'Test',
    'Secondary Diagnosis': '',
    'Supervising Provider': 'Jeffrey Drakos',
    'Organization ID': '30',
    'Organization Name': 'CoachCare',
    Status: 'Active',
    'Activation Date': '04/28/2023',
    'Billing Type': '',
    'Monitoring Type': '',
    'Latest Claim Date 98975': '01/31/2020',
    'Next Claim Requirements 98975': 'N/A',
    'Latest Claim Date 98977': 'N/A',
    'Next Claim Requirements 98977':
      '20 more calendar days; 15 more device transmissions needed',
    'Latest Claim Date 98980': 'N/A',
    'Next Claim Requirements 98980':
      '30 more calendar days; 20 minutes more of monitoring needed; 1 more live interactions (call/visit) needed',
    'Latest Claim Date 98981 (1)': 'N/A',
    'Next Claim Requirements 98981 (1)':
      '98980 requirements not satisfied; 30 more calendar days; 20 minutes more of monitoring needed',
    'Latest Claim Date 98981 (2)': 'N/A',
    'Next Claim Requirements 98981 (2)':
      '98981 requirements not satisfied; 30 more calendar days; 20 minutes more of monitoring needed'
  },
  {
    ID: '9333',
    'First Name': 'Eric',
    'Last Name': 'Di Bari',
    'Date of Birth': '01/01/2000',
    'Device Type': 'BEAT Blood Pressure Cuff',
    'Primary Diagnosis': 'test',
    'Secondary Diagnosis': 'test',
    'Supervising Provider': 'Eric Di Bari',
    'Organization ID': '31',
    'Organization Name': 'CoachCare Clinic Test NY',
    Status: 'Active',
    'Activation Date': '04/27/2023',
    'Billing Type': '',
    'Monitoring Type': '',
    'Latest Claim Date 98975': '01/31/2020',
    'Next Claim Requirements 98975': 'N/A',
    'Latest Claim Date 98977': '01/31/2020',
    'Next Claim Requirements 98977': 'N/A',
    'Latest Claim Date 98980': 'N/A',
    'Next Claim Requirements 98980':
      '20 more calendar days; 10 minutes more of monitoring needed; 1 more live interactions (call/visit) needed',
    'Latest Claim Date 98981 (1)': 'N/A',
    'Next Claim Requirements 98981 (1)':
      '98980 requirements not satisfied; 30 more calendar days; 20 minutes more of monitoring needed',
    'Latest Claim Date 98981 (2)': 'N/A',
    'Next Claim Requirements 98981 (2)':
      '98981 requirements not satisfied; 30 more calendar days; 20 minutes more of monitoring needed'
  }
]

export const allServicesData = [
  {
    ID: '6708',
    'First Name': 'A',
    'Last Name': 'A',
    'Date of Birth': '04/25/1993',
    'RPM Device Type': 'BALANCE Smart Scale',
    'RPM Primary Diagnosis': 'Primary Diagnosis 123',
    'RPM Secondary Diagnosis': 'Secondary Diagnosis 123',
    'RPM Supervising Provider': 'Lascario Pacheco Arrieta',
    'RPM Organization ID': '7048',
    'RPM Organization Name': 'CoachCare Clinic Test',
    'RPM Status': 'Active',
    'RPM Activation Date': '05/01/2023',
    'RPM Billing Type': '',
    'RPM Monitoring Type': '',
    'Latest Claim Date 99453': 'N/A',
    'Latest Claim Date 99454': 'N/A',
    'Latest Claim Date 99457': 'N/A',
    'Latest Claim Date 99458 (1)': 'N/A',
    'Latest Claim Date 99458 (2)': 'N/A',
    'CCM Primary Diagnosis': 'test',
    'CCM Secondary Diagnosis': 'testasdsd',
    'CCM Supervising Provider': 'Eric Di Bari',
    'CCM Organization ID': '7048',
    'CCM Organization Name': 'CoachCare Clinic Test',
    'CCM Status': 'Active',
    'CCM Activation Date': '01/31/2020',
    'CCM Billing Type': '',
    'CCM Monitoring Type': '',
    'Latest Claim Date 99490': 'N/A',
    'Latest Claim Date 99439 (1)': 'N/A',
    'Latest Claim Date 99439 (2)': 'N/A',
    'RTM Device Type': 'SCAN Smart Glucometer',
    'RTM Primary Diagnosis': 'Primary Diagnosis 123',
    'RTM Secondary Diagnosis': 'Secondary Diagnosis 123',
    'RTM Supervising Provider': 'Lascario Pacheco Arrieta',
    'RTM Organization ID': '7048',
    'RTM Organization Name': 'CoachCare Clinic Test',
    'RTM Status': 'Active',
    'RTM Activation Date': '05/01/2023',
    'RTM Billing Type': '',
    'RTM Monitoring Type': '',
    'Latest Claim Date 98975': 'N/A',
    'Latest Claim Date 98977': 'N/A',
    'Latest Claim Date 98980': 'N/A',
    'Latest Claim Date 98981 (1)': 'N/A',
    'Latest Claim Date 98981 (2)': 'N/A',
    'PCM Primary Diagnosis': '',
    'PCM Secondary Diagnosis': '',
    'PCM Supervising Provider': '',
    'PCM Organization ID': '',
    'PCM Organization Name': '',
    'PCM Status': '',
    'PCM Activation Date': '',
    'PCM Billing Type': '',
    'PCM Monitoring Type': '',
    'Latest Claim Date 99426': '',
    'Latest Claim Date 99427 (1)': '',
    'Latest Claim Date 99427 (2)': '',
    'BHI Primary Diagnosis': '',
    'BHI Secondary Diagnosis': '',
    'BHI Supervising Provider': '',
    'BHI Organization ID': '',
    'BHI Organization Name': '',
    'BHI Status': '',
    'BHI Activation Date': '',
    'BHI Billing Type': '',
    'BHI Monitoring Type': '',
    'Latest Claim Date 99484': ''
  },
  {
    ID: '7470',
    'First Name': 'Zhang',
    'Last Name': 'Xin',
    'Date of Birth': '07/22/1994',
    'RPM Device Type': 'BEAT Blood Pressure Cuff',
    'RPM Primary Diagnosis': 'Test',
    'RPM Secondary Diagnosis': '',
    'RPM Supervising Provider': 'Jeffrey Drakos',
    'RPM Organization ID': '30',
    'RPM Organization Name': 'CoachCare',
    'RPM Status': 'Active',
    'RPM Activation Date': '04/28/2023',
    'RPM Billing Type': '',
    'RPM Monitoring Type': '',
    'Latest Claim Date 99453': '01/31/2020',
    'Latest Claim Date 99454': 'N/A',
    'Latest Claim Date 99457': 'N/A',
    'Latest Claim Date 99458 (1)': 'N/A',
    'Latest Claim Date 99458 (2)': 'N/A',
    'CCM Primary Diagnosis': 'sdd',
    'CCM Secondary Diagnosis': 'sdd',
    'CCM Supervising Provider': 'Jeffrey Drakos',
    'CCM Organization ID': '30',
    'CCM Organization Name': 'CoachCare',
    'CCM Status': 'Active',
    'CCM Activation Date': '02/01/2020',
    'CCM Billing Type': '',
    'CCM Monitoring Type': '',
    'Latest Claim Date 99490': '01/31/2020',
    'Latest Claim Date 99439 (1)': '01/31/2020',
    'Latest Claim Date 99439 (2)': '01/31/2020',
    'RTM Device Type': 'BEAT Blood Pressure Cuff',
    'RTM Primary Diagnosis': 'Test',
    'RTM Secondary Diagnosis': '',
    'RTM Supervising Provider': 'Jeffrey Drakos',
    'RTM Organization ID': '30',
    'RTM Organization Name': 'CoachCare',
    'RTM Status': 'Active',
    'RTM Activation Date': '04/28/2023',
    'RTM Billing Type': '',
    'RTM Monitoring Type': '',
    'Latest Claim Date 98975': '01/31/2020',
    'Latest Claim Date 98977': 'N/A',
    'Latest Claim Date 98980': 'N/A',
    'Latest Claim Date 98981 (1)': 'N/A',
    'Latest Claim Date 98981 (2)': 'N/A',
    'PCM Primary Diagnosis': '',
    'PCM Secondary Diagnosis': '',
    'PCM Supervising Provider': '',
    'PCM Organization ID': '',
    'PCM Organization Name': '',
    'PCM Status': '',
    'PCM Activation Date': '',
    'PCM Billing Type': '',
    'PCM Monitoring Type': '',
    'Latest Claim Date 99426': '',
    'Latest Claim Date 99427 (1)': '',
    'Latest Claim Date 99427 (2)': '',
    'BHI Primary Diagnosis': '',
    'BHI Secondary Diagnosis': '',
    'BHI Supervising Provider': '',
    'BHI Organization ID': '',
    'BHI Organization Name': '',
    'BHI Status': '',
    'BHI Activation Date': '',
    'BHI Billing Type': '',
    'BHI Monitoring Type': '',
    'Latest Claim Date 99484': ''
  }
]
