export const COOKIE_CALL_BROWSERS_MODAL = 'ccrCallBrowsersModal'
export const COOKIE_CALL_DEVICES_MODAL = 'ccrCallDevicesModal'
export const STORAGE_PROVIDER_ROUTE = 'ccrProviderRoute'
export const STORAGE_CALL_WINDOW_CORNER = 'ccrCallWindowCorner'
export const STORAGE_PATIENTS_PAGINATION = 'ccrPatientsPagination'
export const STORAGE_COACHES_PAGINATION = 'ccrCoachesPagination'
export const STORAGE_FIRST_TIME_GUIDE = 'ccrFirstTimeGuide'
export const STORAGE_RPM_GUIDE = 'ccrRPMGuide'
export const STORAGE_NEWS_LAST_SEEN_TIMESTAMP = 'ccrNewsLastSeenTimestamp'
export const STORAGE_TIME_TRACKER_STASH = 'ccrTimeTrackerStash'
export const STORAGE_VIDEOCONFERENCE_SETTINGS = 'ccrVideoConferenceSettings'
export const STORAGE_PAGE_SIZE_PATIENT_LISTING =
  'ccrDefaultPageSizePatientListing'
export const STORAGE_RPM_BILLING_SORT = 'ccrRPMBillingsSort'
export const STORAGE_RPM_BILLING_PAGINATION = 'ccrRPMBillingsPagination'
export const STORAGE_PRM_BILLING_FILTER = 'ccrRPMBillingsFilter'
export const STORAGE_RPM_BILLING_COLUMN_INDEX = 'ccrRPMBillingsColumnIndex'
export const STORAGE_PAGE_SIZE_RPM_BILLING = 'ccrDefaultPageSizeRPMBillings'
export const STORAGE_MESSAGE_INPUT_HEIGHT = 'ccrMessageInputHeight'
export const STORAGE_MEASUREMENT_LIST_SORT = 'ccrMeasurementListSort'
export const STORAGE_CARE_MANAGEMENT_SERVICE_TYPE =
  'ccrCareManagementServiceType'
