export * from './apollo/apollo.last-step.component'
export * from './default'
export * from './inhealth'
export * from './itg'
export * from './model'
export * from './shake-it/shake-it.last-step.component'
